import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  buttonBack: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF404A',
    paddingLeft: 15,
    paddingVertical: 10,
  },
  buttonRefresh: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF404A',
    paddingRight: 15,
    paddingVertical: 10,
  },
  buttonBackText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
    textTransform: 'uppercase',
  },
  headerBar: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 15,
    backgroundColor: '#FF404A',
  },
  headerBarText: {
    fontSize: 20,
    color: '#ffffff',
    width: '40%',
  },
  barCodeScannerWrapper: {
    flex: 1,
  },
  barCodeScanner: {
    flex: 1,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  barCodeFocused: {
    width: 200,
    height: 150,
    position: 'relative',
  },
  borderTopLeft: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 25,
    height: 25,
    borderTopWidth: 5,
    borderLeftWidth: 5,
    borderColor: '#ffffff',
    borderTopLeftRadius: 10,
  },
  borderTopRight: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 25,
    height: 25,
    borderTopWidth: 5,
    borderRightWidth: 5,
    borderColor: '#ffffff',
    borderTopRightRadius: 10,
  },
  borderBottomLeft: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: 25,
    height: 25,
    borderBottomWidth: 5,
    borderLeftWidth: 5,
    borderColor: '#ffffff',
    borderBottomLeftRadius: 10,
  },
  borderBottomRight: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 25,
    height: 25,
    borderBottomWidth: 5,
    borderRightWidth: 5,
    borderColor: '#ffffff',
    borderBottomRightRadius: 10,
  },
  alternativeChoiceButton: {
    bottom: -200,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  alternativeChoiceButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  barCodeScannedView: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  scannedButton: {
    backgroundColor: 'blue',
    padding: 10,
  },
  scannedButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  inputBarCodeView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputBarCodeWrapper: {
    width: '60%',
    position: 'relative',
  },
  inputBarCodeLabel: {
    position: 'absolute',
    top: -10,
    left: 20,
    zIndex: 1,
    paddingHorizontal: 5,
    backgroundColor: '#fff',
  },
  inputBarCode: {
    paddingLeft: 10,
    color: '#FF404A',
    width: '100%',
    height: 60,
    fontSize: 18,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: 'rgba(0,0,0,.12)',
  },
  switchToCamera: {
    padding: 20,
    marginTop: 50,
  },
});
